---
firewall_state: started
firewall_enabled_at_boot: true

firewall_flush_rules_and_chains: true

firewall_allowed_tcp_ports:
  - "80"
  - "443"
firewall_allowed_udp_ports: []
firewall_forwarded_tcp_ports: []
firewall_forwarded_udp_ports: []
firewall_additional_rules: []
firewall_enable_ipv6: false
firewall_ip6_additional_rules: []
firewall_log_dropped_packets: true

# Set to true to ensure other firewall management software is disabled.
firewall_disable_firewalld: true
firewall_disable_ufw: true