###############################################################
#                   Authelia configuration                    #
###############################################################

host: 0.0.0.0
port: 9091
log_level: debug
# This secret can also be set using the env variables AUTHELIA_JWT_SECRET
jwt_secret: fhK7x5y3MPPLbaTFfhK7x5y3MPPLbaTF
default_redirection_url: https://whoami.{{ domain }}
totp:
  issuer: {{ domain }}
  period: 30
  skew: 1

#duo_api:
#  hostname: api-123456789.example.com
#  integration_key: ABCDEF
#  # This secret can also be set using the env variables AUTHELIA_DUO_API_SECRET_KEY
#  secret_key: 1234567890abcdefghifjkl

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: deny
  rules:
    # Rules applied to everyone
    - domain: whoami.{{ domain }}
      policy: bypass
    - domain: "*.{{ domain }}"
      subject:
        - "group:admins"
      policy: one_factor

session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET
  secret: 9kNDxjPEV9eMa2zA9kNDxjPEV9eMa2zA
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
  domain: {{ domain }} # Should match whatever your root protected domain is

  redis:
    host: authelia-redis
    port: 6379
    # This secret can also be set using the env variables AUTHELIA_SESSION_REDIS_PASSWORD
    #password: authelia

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /tmp/authelia/notification.txt
